### ISSUE TITLE
Use Cbc installed version

### ISSUE THREAD

**Issue by Blue-Pix** [gverger/cbc-wrapper#5]
when I try to install cbc-wrapper, actually in CircleCI build phase, I had following error.
Because `www.coin-or.org` server is down.
Since May 2019, same problem occurs several times a week.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/home/circleci/my-app/vendor/bundle/ruby/2.5.0/gems/cbc-wrapper-2.9.9.3/ext/cbc-wrapper
/usr/local/bin/ruby -r ./siteconf20190610-132-o4n71g.rb extconf.rb

...

curl: (7) Failed to connect to www.coin-or.org
port 443: Connection timed out
tar (child): /tmp/Cbc.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sh: 1: cd: can't cd to /tmp/Cbc-2.9.9
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
Failed to build CBC, aborting... Cbc source is in /tmp/Cbc-2.9.9

extconf failed, exit code 1
```

I would like to install cbc in advance, and expect gem use that version.
I found closed pull request below, you may be already to merge to master?
https://github.com/gverger/cbc-wrapper/pull/3#issuecomment-426007154

I would appreciate if you could considering it.
Thanks😁

**Comment by gverger** [comment]
Hello, I am sorry you are not able to use the gem properly.

I will merge the branch to master. It has been a while since I didn't look at it, I will try and review it a bit first.
My concern is that it will break other users installations when they will update the gem once merged.

In the meantime, can you use the branch mentioned there?
I am not using the gem right now, and I would like to make sure other people are able to use it before I mess with it.

**Comment by Blue-Pix** [comment]
Sure. I'll try it.

**Comment by j10k** [comment]
Hi, I have been using this gem for a few years now, and as you foresaw this update broke my installation. I would gladly install coinor-cbc myself so that I am not stuck on 2.9.9.3, but I do not know how.

I assumed installing the `coinor-cbc` package for my distribution (Ubuntu 18.04 LTS) would do the trick, and I can actually run the cbc binary. However installation of the gem fails : `checking for -lCbcSolver... no`. Running ` ldconfig -p | grep cbc` confirms that the library is not installed.

Maybe the best approach might be to install cbc as in 2.9.9.3, but first check if a suitable version is already installed? I understand that you have not been working on the library a lot, and I would also be happy if you could you add the required steps to the installation section of the Readme, of course.

**Comment by gverger** [comment]
Hi, thanks for the feedback. I have had another issue open in `ruby-cbc`, where it has been said that the package `coinor-libcbc-dev` has to be installed for ubuntu. See https://github.com/gverger/ruby-cbc/issues/22#issue-665478150

Apologies for that, I will try to update the readme accordingly, but I am having other priorities right now. I'll try and do it in a "near" future though.

**Comment by gverger** [comment]
Readme of this gem and `ruby-cbc` have been updated.

I am closing this issue.

Please open a new one if any installation problem occurs
